ktor_version=3.3.3
kotlin_version=2.3.0
logback_version=1.5.32
kotlin.code.style=official
tokensupport_version=5.0.30
mockoath_version=3.0.3
kotest_version=6.1.11
prometheus_version=1.16.5
logstash_encoder_version=9.0
valkey_java_version=5.5.0
arrow_version=2.2.2.1
poao_tilgang_version=4.2026.05.07_06.50-2df9ab3eceaf
common_version=4.2026.05.05_06.25-f72fab488a93
kotest_extensions_version=6.1.11
