ktor_version=3.6.0
kotlin_version=2.4.0
logback_version=1.5.37
kotlin.code.style=official
tokensupport_version=6.0.12
mockoath_version=5.0.2
kotest_version=6.2.1
prometheus_version=1.16.5
logstash_encoder_version=9.0
valkey_java_version=5.5.0
arrow_version=2.2.3
poao_tilgang_version=4.2026.09.14_09.01-2100e3faec2d
common_version=4.2026.09.14_05.57-40a1ead1e559
