ktor_version=3.4.0
kotlin_version=2.3.21
logback_version=1.5.32
kotlin.code.style=official
tokensupport_version=6.0.8
mockoath_version=3.0.3
kotest_version=6.1.11
prometheus_version=1.16.5
logstash_encoder_version=9.0
valkey_java_version=5.5.0
arrow_version=2.2.2.1
poao_tilgang_version=4.2026.06.03_06.17-9fbee8d2bb00
common_version=4.2026.05.29_05.35-a81a45859c9c
kotest_extensions_version=6.1.11
