ktor:
  deployment:
    connectionGroupSize: 16
    workerGroupSize: 16
    callGroupSize: 32
    port: 8080
  application:
    modules:
      - no.nav.please.ApplicationKt.module

topic:
  ny-dialog: "dab.dialog-events-v1"

redis:
  host: "$REDIS_URI_PLEASE:null"
  username: "$REDIS_USERNAME_PLEASE:null"
  password: "$REDIS_PASSWORD_PLEASE:null"
  channel: "dab.dialog-events-v1"

no:
  nav:
    security:
      jwt:
        issuers:
          - discoveryurl: "$AZURE_APP_WELL_KNOWN_URL:null"
            accepted_audience: "$AZURE_APP_CLIENT_ID:null"
            issuer_name: "AzureAD"
          - discoveryurl: "$TOKEN_X_WELL_KNOWN_URL:null"
            accepted_audience: "$TOKEN_X_CLIENT_ID:null"
            issuer_name: "TokenX"

azure:
  client-id: "$AZURE_APP_CLIENT_ID"
  token-endpoint: "$AZURE_OPENID_CONFIG_TOKEN_ENDPOINT"
  client-secret: "$AZURE_APP_CLIENT_SECRET"

poao-tilgang:
  url: "$POAO_TILGANG_CLIENT_URL"
  token-scope: "$POAO_TILGANG_CLIENT_SCOPE"
