kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: please
  namespace: dab
  cluster: dev-gcp
  labels:
    team: dab
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  image: ghcr.io/navikt/please:{{version}}
  ingresses:
    - https://please.ekstern.dev.nav.no
  port: 8080
  redis:
    - instance: please
      access: readwrite
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbdialog
          namespace: pto
          cluster: dev-fss
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
    outbound:
      rules:
        - application: poao-tilgang
          namespace: poao
  env:
    - name: POAO_TILGANG_CLIENT_URL
      value: http://poao-tilgang.poao.svc.cluster.local
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default