kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: please
  namespace: dab
  labels:
    team: dab
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    config.linkerd.io/proxy-cpu-limit: 500m
spec:
  image: {{ image }}
  ingresses:
    - https://please.nav.no
  port: 8080
  redis:
    - instance: please
      access: readwrite
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbdialog
          namespace: pto
          cluster: prod-fss
        - application: veilarbdialog
          namespace: dab
          cluster: prod-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp