name: Deploy PLEASE main branch to dev and prod
run-name:  Deploy PLEASE main branch to dev and prod by @${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy_prod
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  dev:
    name: Deploy to dev
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
      NAIS_MANAGEMENT_PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  prod:
    name: Deploy to prod
    uses: ./.github/workflows/deploy.yml
    with:
      env: prod
      NAIS_MANAGEMENT_PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
