name: Deploy PLEASE feature branch to dev
run-name:  Deploy PLEASE feature branch ${{ github.ref_name }} to dev by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  dev:
    name: Deploy to dev
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
      NAIS_MANAGEMENT_PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}