on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      NAIS_DEPLOY_APIKEY:
        required: true

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test-build-and-push:
    name: Test, build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    - name: PLEASE - Test
      run: ./gradlew test
    - name: PLEASE - Publish image
      run: ./gradlew publishImage --scan
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy application
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: ${{ inputs.env }}-gcp
        RESOURCE: nais/nais-${{ inputs.env }}.yaml
        VAR: version=${{ env.IMAGE_TAG }}
    - name: Slack Notification (deploy failure)
      if: failure() && inputs.env == 'prod'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: danger
        SLACK_USERNAME: Github Actions
        SLACK_ICON: https://github.com/github.png?size=48
        SLACK_TITLE: 'Please: deploy til prod feilet'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Commit-message til feilende deploy: ${{ github.event.head_commit.message }}'